version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    container_name: backend_service
    restart: unless-stopped
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=backend.settings
    working_dir: /app
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: postgres_service
    restart: unless-stopped
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  client:
    build:
      context: ./client
      dockerfile: ../docker/client/Dockerfile
    container_name: frontend_service
    command: sh -c "npm install && npx nuxt dev --hostname 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - client
  
  ollama:
    build:
      context: ./docker/ollama
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  postgres_data:
  node_modules:
  ollama_data: